name: Progress Bar CI

on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
    - cron: '10 */12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.0.0'
    - name: Update README.md
      run: node index.js > quotes.txt
    - name: Commit change & Push
      run: |
          git config user.name 'Ashirvad-Kumar-Pandey-1-618'
          git config user.email 'ashirvadpandey1@gmail.com'
          git commit -am "plant some tree 🌳"
          git push
